

services:
  db:
    image: postgres:15-alpine
    container_name: bank-db
    restart: always
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank_user -d bank_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: bank-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bank_db
      SPRING_DATASOURCE_USERNAME: bank_user
      SPRING_DATASOURCE_PASSWORD: bank_password
      SPRING_LIQUIBASE_ENABLED: "true"
      JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: